version: 2.1

orbs:
  yarn: artsy/yarn@1.1.0

jobs:
  housekeeping:
    - yarn/run-script:
        script: lint
        description: Linting
    - yarn/run-script:
        script: type-check
        description: Verifying Typescript types

workflows:
  main:
    jobs:
      - yarn/update-cache
      - housekeeping
      - yarn/jest
      - yarn/auto-release:
          # The deploy job is the _only_ job that should have access to our npm
          # tokens. We include a context that has our publish credentials
          # explicitly in this step. https://circleci.com/docs/2.0/contexts/
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/jest
            - housekeeping
