version: 2.1

orbs:
  yarn: artsy/yarn@1.1.0

jobs:
  build:
    - yarn/setup
    - run: yarn lint
    - run: yarn type-check
    - run: yarn jest
    - run: yarn build

workflows:
  main:
    jobs:
      - yarn/update-cache
      - build
      - yarn/auto-release:
          # The deploy job is the _only_ job that should have access to our npm
          # tokens. We include a context that has our publish credentials
          # explicitly in this step. https://circleci.com/docs/2.0/contexts/
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - build
